# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/savoji/Desktop/term7/OS/course projects/ca3/os_multi_thread"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/savoji/Desktop/term7/OS/course projects/ca3/os_multi_thread"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/savoji/Desktop/term7/OS/course projects/ca3/os_multi_thread/CMakeFiles" "/home/savoji/Desktop/term7/OS/course projects/ca3/os_multi_thread/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/savoji/Desktop/term7/OS/course projects/ca3/os_multi_thread/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named p3

# Build rule for target.
p3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 p3
.PHONY : p3

# fast build rule for target.
p3/fast:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/build
.PHONY : p3/fast

src/Edge.o: src/Edge.cpp.o

.PHONY : src/Edge.o

# target to build an object file
src/Edge.cpp.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Edge.cpp.o
.PHONY : src/Edge.cpp.o

src/Edge.i: src/Edge.cpp.i

.PHONY : src/Edge.i

# target to preprocess a source file
src/Edge.cpp.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Edge.cpp.i
.PHONY : src/Edge.cpp.i

src/Edge.s: src/Edge.cpp.s

.PHONY : src/Edge.s

# target to generate assembly for a file
src/Edge.cpp.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Edge.cpp.s
.PHONY : src/Edge.cpp.s

src/Graph.o: src/Graph.cpp.o

.PHONY : src/Graph.o

# target to build an object file
src/Graph.cpp.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Graph.cpp.o
.PHONY : src/Graph.cpp.o

src/Graph.i: src/Graph.cpp.i

.PHONY : src/Graph.i

# target to preprocess a source file
src/Graph.cpp.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Graph.cpp.i
.PHONY : src/Graph.cpp.i

src/Graph.s: src/Graph.cpp.s

.PHONY : src/Graph.s

# target to generate assembly for a file
src/Graph.cpp.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Graph.cpp.s
.PHONY : src/Graph.cpp.s

src/Path.o: src/Path.cpp.o

.PHONY : src/Path.o

# target to build an object file
src/Path.cpp.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Path.cpp.o
.PHONY : src/Path.cpp.o

src/Path.i: src/Path.cpp.i

.PHONY : src/Path.i

# target to preprocess a source file
src/Path.cpp.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Path.cpp.i
.PHONY : src/Path.cpp.i

src/Path.s: src/Path.cpp.s

.PHONY : src/Path.s

# target to generate assembly for a file
src/Path.cpp.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/Path.cpp.s
.PHONY : src/Path.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/p3.dir/build.make CMakeFiles/p3.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... p3"
	@echo "... edit_cache"
	@echo "... src/Edge.o"
	@echo "... src/Edge.i"
	@echo "... src/Edge.s"
	@echo "... src/Graph.o"
	@echo "... src/Graph.i"
	@echo "... src/Graph.s"
	@echo "... src/Path.o"
	@echo "... src/Path.i"
	@echo "... src/Path.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

